# Define the services, 'neo4j' in this case
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP port for the Neo4j Browser
      - "7687:7687"  # Bolt port for drivers (like from Python)
    environment:
      # Set the default username/password. CHANGE 'StrongPassword123' in production
      - NEO4J_AUTH=neo4j/StrongPassword123
      # Automatically include the APOC (Awesome Procedures on Cypher) plugin
      - NEO4JLABS_PLUGINS=["apoc"]
      # Allow APOC procedures to be called
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      # Mount the named volumes defined below into the container
      - neo4j_data:/data
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_plugins:
